local AddOnName, AddOn = ...
local L = LibStub("AceLocale-3.0"):NewLocale(AddOnName, "ruRU", false)

L.ADDON_NAME = "Immersive"

-- Bindings
BINDING_HEADER_IMMERSIVE = "Управление Immersive"
BINDING_NAME_IMMERSIVE_PANIC = "Активировать режим паники"

-- Framework
L.FRAMEWORK_PANIC_MODE_ACTIVATE = "Режим паники активирован!"
L.FRAMEWORK_PANIC_MODE_DEACTIVATE = "Режим паники деактивирован!"

-- Api Module
L.API_MODE_ALL_TITLE = "Условный (Все)"
L.API_MODE_ANY_TITLE = "Условный (Любой)"
L.API_MODE_HIDDEN_TITLE = "Всегда скрыт"

-- Configuration Module
L.CONFIG_CPU_USAGE = "Использование ЦП (в секунду): %.2f%%"
L.CONFIG_RELOAD_REQUIRED = "CVar 'scriptProfile' включен. Требуется перезагрузка интерфейса."
L.CONFIG_SLIDER_FORMATTED_TEXT = "%s (%sс)"
L.CONFIG_SLIDER_TYPE_DELAY_TEXT = "Задержка"
L.CONFIG_SLIDER_TYPE_FADE_TEXT = "Затухание"

L.CONFIG_OPTIONS_NAME = "Immersive"
L.CONFIG_OPTIONS_TITLE = "Immersive"
L.CONFIG_OPTIONS_SUBTEXT = "Эти настройки влияют на Immersive и все его активные модули."
L.CONFIG_OPTIONS_PERFORMANCE_FORMATTED_TEXT = "Производительность (%sмс)"
L.CONFIG_OPTIONS_PERFORMANCE_TOOLTIP = "Настраивает отзывчивость Immersive при проверке условий и точек активности. Уменьшение этого значения повысит отзывчивость, но значительно снизит производительность клиента WoW, увеличение может вызвать задержку при затухании элементов интерфейса, но улучшит производительность на старых машинах. Рекомендуемая настройка — 100 миллисекунд."
L.CONFIG_OPTIONS_DEBUG_TEXT = "Режим отладки"
L.CONFIG_OPTIONS_DEBUG_TOOLTIP = "Включает режим разработчика."
L.CONFIG_OPTIONS_PANICSTARTUP_TEXT = "Паника при запуске"
L.CONFIG_OPTIONS_PANICSTARTUP_TOOLTIP = "Активирует режим паники при входе в World of Warcraft."
L.CONFIG_OPTIONS_ACTIONCAM_TITLE = "Экшн-камера"
L.CONFIG_OPTIONS_ACTIONCAM_TOOLTIP = "Устанавливает режим функции экшн-камеры."
L.CONFIG_OPTIONS_VERSION_TEXT = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|t Текущая версия аддона: v%s"

L.CONFIG_OPTIONS_PROFILES_NAME = "Профили"
L.CONFIG_OPTIONS_PROFILES_TITLE = "Профили"
L.CONFIG_OPTIONS_PROFILES_SUBTEXT = "Эти настройки влияют на текущий активный профиль настроек."
L.CONFIG_OPTIONS_PROFILES_RESET_TEXT = "Сбросить настройки текущего активного профиля на значения по умолчанию"
L.CONFIG_OPTIONS_PROFILES_RESET_TITLE = "Сброс профиля"
L.CONFIG_OPTIONS_PROFILES_RESET_TOOLTIP = "Все настройки текущего активного профиля будут сброшены на значения по умолчанию."
L.CONFIG_OPTIONS_PROFILES_RESET_PROFILE = "|cffffbb00Текущий профиль:|cffffffff %s"
L.CONFIG_OPTIONS_PROFILES_COPY_TEXT = "Скопировать настройки из существующего профиля в текущий активный профиль."
L.CONFIG_OPTIONS_PROFILES_COPY_TITLE = "Существующие профили"
L.CONFIG_OPTIONS_PROFILES_COPY_TOOLTIP = "Настройки выбранного существующего профиля будут скопированы в текущий активный профиль."

L.CONFIG_OPTIONS_PROFILES_RESET_CONFIRM = "Вы уверены, что хотите сбросить текущий активный профиль на значения по умолчанию?"
L.CONFIG_OPTIONS_PROFILES_RESET_CONFIRM_YES = "Да"
L.CONFIG_OPTIONS_PROFILES_RESET_CONFIRM_NO = "Нет"
L.CONFIG_OPTIONS_PROFILES_COPY_CONFIRM = "Вы уверены, что хотите перезаписать текущий активный профиль настройками выбранного существующего профиля?"
L.CONFIG_OPTIONS_PROFILES_COPY_CONFIRM_YES = "Да"
L.CONFIG_OPTIONS_PROFILES_COPY_CONFIRM_NO = "Нет"

L.CONFIG_OPTIONS_RELOAD_REQUIRED = "Для применения выбранных изменений требуется перезагрузка интерфейса. Перезагрузить интерфейс сейчас?"
L.CONFIG_OPTIONS_RELOAD_REQUIRED_YES = "Да"
L.CONFIG_OPTIONS_RELOAD_REQUIRED_NO = "Нет"

-- Default Module
L.DEFAULT_DEBUG_WELCOME = "Привет, |c%s%s|cffffffff, приготовьтесь к погружению!"

L.DEFAULT_CLASSIC_BUFF_FRAME_TITLE = "Баффы"
L.DEFAULT_CLASSIC_MAIN_MENU_BAR_TITLE = "Основная панель действий"
L.DEFAULT_CLASSIC_EXPERIENCE_BAR_TITLE = "Полоса опыта"
L.DEFAULT_CLASSIC_MICRO_BUTTON_AND_BAGS_BAR_TITLE = "Микрокнопки и панель сумок"
L.DEFAULT_CLASSIC_MINIMAP_CLUSTER_TITLE = "Миникарта"
L.DEFAULT_CLASSIC_MULTIBAR_BOTTOM_LEFT_TITLE = "Нижняя левая панель действий"
L.DEFAULT_CLASSIC_MULTIBAR_BOTTOM_RIGHT_TITLE = "Нижняя правая панель действий"
L.DEFAULT_CLASSIC_MULTIBAR_LEFT_TITLE = "Боковая левая панель действий"
L.DEFAULT_CLASSIC_MULTIBAR_RIGHT_TITLE = "Боковая правая панель действий"
L.DEFAULT_CLASSIC_OBJECTIVE_TRACKER_FRAME_TITLE = "Отслеживание заданий"
L.DEFAULT_CLASSIC_ORDER_HALL_COMMAND_BAR_TITLE = "Панель управления орденом"
L.DEFAULT_CLASSIC_PARTY_MEMBER_FRAME_TITLE = "Члены группы"
L.DEFAULT_CLASSIC_PET_ACTION_BAR_FRAME_TITLE = "Панель действий питомца"
L.DEFAULT_CLASSIC_PLAYER_FRAME_TITLE = "Рамка здоровья игрока"
L.DEFAULT_CLASSIC_COMPACT_RAID_FRAME_TITLE = "Члены рейда"
L.DEFAULT_CLASSIC_STANCE_BAR_FRAME_TITLE = "Панель стоек"
L.DEFAULT_CLASSIC_TARGET_FRAME_TITLE = "Рамка здоровья цели"
L.DEFAULT_CLASSIC_VEHICLE_LEAVE_BUTTON_TITLE = "Кнопка выхода из транспорта"
L.DEFAULT_CLASSIC_VEHICLE_SEAT_INDICATOR_TITLE = "Индикатор сидений транспорта"

L.DEFAULT_BUFF_FRAME_TITLE = "Баффы"
L.DEFAULT_MAIN_MENU_BAR_TITLE = "Панель действий 1"
L.DEFAULT_EXPERIENCE_BAR_TITLE = "Полоса опыта"
L.DEFAULT_MICRO_BUTTON_AND_BAGS_BAR_TITLE = "Микрокнопки и панель сумок"
L.DEFAULT_MINIMAP_CLUSTER_TITLE = "Миникарта"
L.DEFAULT_MULTIBAR_BOTTOM_LEFT_TITLE = "Панель действий 2"
L.DEFAULT_MULTIBAR_BOTTOM_RIGHT_TITLE = "Панель действий 3"
L.DEFAULT_MULTIBAR_LEFT_TITLE = "Панель действий 5"
L.DEFAULT_MULTIBAR_RIGHT_TITLE = "Панель действий 4"
L.DEFAULT_MULTIBAR_5_TITLE = "Панель действий 6"
L.DEFAULT_MULTIBAR_6_TITLE = "Панель действий 7"
L.DEFAULT_MULTIBAR_7_TITLE = "Панель действий 8"
L.DEFAULT_OBJECTIVE_TRACKER_FRAME_TITLE = "Отслеживание заданий"
L.DEFAULT_ORDER_HALL_COMMAND_BAR_TITLE = "Панель управления орденом"
L.DEFAULT_PARTY_MEMBER_FRAME_TITLE = "Члены группы"
L.DEFAULT_PET_ACTION_BAR_FRAME_TITLE = "Панель действий питомца"
L.DEFAULT_PLAYER_FRAME_TITLE = "Рамка здоровья игрока"
L.DEFAULT_COMPACT_RAID_FRAME_TITLE = "Члены рейда"
L.DEFAULT_STANCE_BAR_FRAME_TITLE = "Панель стоек"
L.DEFAULT_TARGET_FRAME_TITLE = "Рамка здоровья цели"
L.DEFAULT_VEHICLE_LEAVE_BUTTON_TITLE = "Кнопка выхода из транспорта"
L.DEFAULT_VEHICLE_SEAT_INDICATOR_TITLE = "Индикатор сидений транспорта"

L.DEFAULT_AFK_CONDITION_TITLE = "Игрок в режиме AFK"
L.DEFAULT_AFK_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок помечен как отсутствующий."
L.DEFAULT_ALT_DOWN_CONDITION_TITLE = "Клавиша Alt нажата"
L.DEFAULT_ALT_DOWN_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если клавиша Alt нажата."
L.DEFAULT_BUFF_ACTIVE_CONDITION_TITLE = "Бафф активен"
L.DEFAULT_BUFF_ACTIVE_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если у игрока есть один или несколько активных баффов."
L.DEFAULT_CONTROL_DOWN_CONDITION_TITLE = "Клавиша Ctrl нажата"
L.DEFAULT_CONTROL_DOWN_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если клавиша Ctrl нажата."
L.DEFAULT_DEBUFF_ACTIVE_CONDITION_TITLE = "Дебафф активен"
L.DEFAULT_DEBUFF_ACTIVE_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если у игрока есть один или несколько активных дебаффов."
L.DEFAULT_DND_CONDITION_TITLE = "Игрок в режиме DND"
L.DEFAULT_DND_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок помечен как не беспокоить."
L.DEFAULT_FLYING_CONDITION_TITLE = "Игрок в полете"
L.DEFAULT_FLYING_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится в полете."
L.DEFAULT_HUNGRY_CONDITION_TITLE = "Игрок не на полном здоровье"
L.DEFAULT_HUNGRY_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если у игрока не полное здоровье."
L.DEFAULT_IN_ARENA_CONDITION_TITLE = "На арене"
L.DEFAULT_IN_ARENA_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится на арене."
L.DEFAULT_IN_BATTLEGROUND_CONDITION_TITLE = "На поле боя"
L.DEFAULT_IN_BATTLEGROUND_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится на поле боя."
L.DEFAULT_IN_COMBAT_CONDITION_TITLE = "В бою"
L.DEFAULT_IN_COMBAT_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится в бою."
L.DEFAULT_IN_DUNGEON_INSTANCE_CONDITION_TITLE = "В подземелье"
L.DEFAULT_IN_DUNGEON_INSTANCE_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится в подземелье."
L.DEFAULT_IN_PARTY_CONDITION_TITLE = "В группе"
L.DEFAULT_IN_PARTY_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится в группе."
L.DEFAULT_IN_PET_BATTLE_CONDITION_TITLE = "В битве питомцев"
L.DEFAULT_IN_PET_BATTLE_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок участвует в битве питомцев."
L.DEFAULT_IN_RAID_CONDITION_TITLE = "В рейде"
L.DEFAULT_IN_RAID_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится в рейдовой группе."
L.DEFAULT_IN_RAID_INSTANCE_CONDITION_TITLE = "В рейдовом подземелье"
L.DEFAULT_IN_RAID_INSTANCE_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится в рейдовом подземелье."
L.DEFAULT_IN_SCENARIO_CONDITION_TITLE = "В сценарии"
L.DEFAULT_IN_SCENARIO_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится в сценарии."
L.DEFAULT_IN_VEHICLE_CONDITION_TITLE = "В транспорте"
L.DEFAULT_IN_VEHICLE_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится в транспорте."
L.DEFAULT_INDOORS_CONDITION_TITLE = "Игрок в помещении"
L.DEFAULT_INDOORS_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится в помещении."
L.DEFAULT_MOVING_CONDITION_TITLE = "Игрок движется"
L.DEFAULT_MOVING_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок движется."
L.DEFAULT_OUTDOORS_CONDITION_TITLE = "Игрок на открытом воздухе"
L.DEFAULT_OUTDOORS_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится на открытом воздухе."
L.DEFAULT_PARTY_HUNGRY_CONDITION_TITLE = "Член группы не на полном здоровье (только для лекарей)"
L.DEFAULT_PARTY_HUNGRY_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если член группы не на полном здоровье (только для лекарей)."
L.DEFAULT_RAID_HUNGRY_CONDITION_TITLE = "Член рейда не на полном здоровье (только для лекарей)"
L.DEFAULT_RAID_HUNGRY_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если член рейда не на полном здоровье (только для лекарей)."
L.DEFAULT_RESTING_CONDITION_TITLE = "Игрок отдыхает"
L.DEFAULT_RESTING_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится в зоне отдыха."
L.DEFAULT_ROLE_DAMAGER_CONDITION_TITLE = "Игрок — дамагер"
L.DEFAULT_ROLE_DAMAGER_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если роль игрока — дамагер."
L.DEFAULT_ROLE_HEALER_CONDITION_TITLE = "Игрок — лекарь"
L.DEFAULT_ROLE_HEALER_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если роль игрока — лекарь."
L.DEFAULT_ROLE_TANK_CONDITION_TITLE = "Игрок — танк"
L.DEFAULT_ROLE_TANK_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если роль игрока — танк."
L.DEFAULT_SHIFT_DOWN_CONDITION_TITLE = "Клавиша Shift нажата"
L.DEFAULT_SHIFT_DOWN_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если клавиша Shift нажата."
L.DEFAULT_STATIONARY_CONDITION_TITLE = "Игрок неподвижен"
L.DEFAULT_STATIONARY_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок неподвижен."
L.DEFAULT_STEALTHED_CONDITION_TITLE = "Игрок в скрытности"
L.DEFAULT_STEALTHED_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок находится в скрытности."
L.DEFAULT_SWIMMING_CONDITION_TITLE = "Игрок плавает"
L.DEFAULT_SWIMMING_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если игрок плавает."
L.DEFAULT_TARGET_AVAILABLE_CONDITION_TITLE = "Цель доступна"
L.DEFAULT_TARGET_AVAILABLE_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если у игрока есть цель."
L.DEFAULT_TARGET_ENEMY_CONDITION_TITLE = "Цель — враг"
L.DEFAULT_TARGET_ENEMY_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если текущая цель игрока считается врагом."
L.DEFAULT_TARGET_HOSTILE_CONDITION_TITLE = "Цель нейтральна/враждебна"
L.DEFAULT_TARGET_HOSTILE_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если текущая цель игрока нейтральна/враждебна."
L.DEFAULT_TARGET_IN_PARTY_CONDITION_TITLE = "Цель в группе"
L.DEFAULT_TARGET_IN_PARTY_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если текущая цель игрока находится в группе."
L.DEFAULT_TARGET_IN_RAID_CONDITION_TITLE = "Цель в рейде"
L.DEFAULT_TARGET_IN_RAID_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если текущая цель игрока находится в рейде."
L.DEFAULT_TARGET_PLAYER_CONDITION_TITLE = "Цель — другой игрок"
L.DEFAULT_TARGET_PLAYER_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если текущая цель игрока — другой игрок."
L.DEFAULT_THIRSTY_CONDITION_TITLE = "Игрок не на полной мане"
L.DEFAULT_THIRSTY_CONDITION_TOOLTIP = "Установите флажок, чтобы отображать элемент, если у игрока не полная мана (только для классов с маной)."

L.DEFAULT_OPTIONS_NAME = "Интерфейс по умолчанию"
L.DEFAULT_OPTIONS_TITLE = "Стандартный интерфейс Blizzard"
L.DEFAULT_OPTIONS_SUBTEXT = "Эти настройки влияют на поведение всех поддерживаемых элементов стандартного интерфейса."
L.DEFAULT_OPTIONS_ENABLED_TEXT = "Включено"
L.DEFAULT_OPTIONS_ENABLED_TOOLTIP = "Включить или отключить модуль стандартного интерфейса."
L.DEFAULT_OPTIONS_ELEMENT_ENABLED_TOOLTIP = "Установите флажок, чтобы включить автоматическое отображение %s."
L.DEFAULT_OPTIONS_HOTSPOT_TEXT = "Включить точку активности"
L.DEFAULT_OPTIONS_HOTSPOT_TOOLTIP = "Установите флажок, чтобы включить возможность активации и отображения элемента при наведении мыши на его область."
L.DEFAULT_OPTIONS_MODE_TITLE = "Режим:"
L.DEFAULT_OPTIONS_MODE_TOOLTIP = ""

-- Chat Module
L.CHAT_MODE_GEMS_TITLE = "Чат-геммы"
L.CHAT_MODE_GEMS_CONTROLLER_TOOLTIP = "Нажмите, чтобы открыть чат."
L.CHAT_MODE_GEMS_CHANNEL_TOOLTIP_READ = "Нет непрочитанных сообщений."
L.CHAT_MODE_GEMS_CHANNEL_TOOLTIP_UNREAD = "%d непрочитанных сообщений."

L.CHAT_MSG_SAY = "Сказать"
L.CHAT_MSG_YELL = "Крик"
L.CHAT_MSG_BN_WHISPER = "Шепот Battle.Net"
L.CHAT_MSG_WHISPER = "Шепот"
L.CHAT_MSG_GUILD = "Гильдия"
L.CHAT_MSG_OFFICER = "Офицер"
L.CHAT_MSG_PARTY = "Группа"
L.CHAT_MSG_PARTY_LEADER = "Лидер группы"
L.CHAT_MSG_RAID = "Рейд"
L.CHAT_MSG_RAID_LEADER = "Лидер рейда"
L.CHAT_MSG_RAID_WARNING = "Предупреждение рейда"
L.CHAT_MSG_INSTANCE_CHAT = "Чат подземелья"
L.CHAT_MSG_INSTANCE_CHAT_LEADER = "Лидер чата подземелья"

L.CHAT_OPTIONS_NAME = "Чат"
L.CHAT_OPTIONS_TITLE = "Окна чата"
L.CHAT_OPTIONS_SUBTEXT = "Эти настройки влияют на поведение всех окон чата."
L.CHAT_OPTIONS_ENABLED_TEXT = "Включено"
L.CHAT_OPTIONS_ENABLED_TOOLTIP = "Включить или отключить модуль чата."
L.CHAT_OPTIONS_HOTSPOT_TEXT = "Включить точку активности"
L.CHAT_OPTIONS_HOTSPOT_TOOLTIP = "Установите флажок, чтобы включить возможность активации и отображения окна чата при наведении мыши на его область."
L.CHAT_OPTIONS_MODE_TITLE = "Режим:"
L.CHAT_OPTIONS_MODE_TOOLTIP = ""
L.CHAT_OPTIONS_ANCHOR_TITLE = "Якорь:"
L.CHAT_OPTIONS_ANCHOR_TOOLTIP = ""
L.CHAT_OPTIONS_ANCHOR_TOPLEFT = "Верхний левый"
L.CHAT_OPTIONS_ANCHOR_TOPRIGHT = "Верхний правый"
L.CHAT_OPTIONS_ANCHOR_BOTTOMLEFT = "Нижний левый"
L.CHAT_OPTIONS_ANCHOR_BOTTOMRIGHT = "Нижний правый"
L.CHAT_OPTIONS_DIRECTION_TITLE = "Направление:"
L.CHAT_OPTIONS_DIRECTION_TOOLTIP = ""
L.CHAT_OPTIONS_DIRECTION_HORIZONTAL = "Горизонтальное"
L.CHAT_OPTIONS_DIRECTION_VERTICAL = "Вертикальное"
L.CHAT_OPTIONS_MOVING_TEXT = "Включить перемещение"
L.CHAT_OPTIONS_MOVING_TOOLTIP = "Установите флажок, чтобы включить возможность скрывать чат-геммы во время движения."

-- ElvUI Module
L.ELVUI_OPTIONS_NAME = "ElvUI"
L.ELVUI_OPTIONS_TITLE = "ElvUI"
L.ELVUI_OPTIONS_SUBTEXT = "Эти настройки влияют на поведение всех поддерживаемых элементов ElvUI."
L.ELVUI_OPTIONS_ENABLED_TEXT = "Включено"
L.ELVUI_OPTIONS_ENABLED_TOOLTIP = "Включить или отключить модуль ElvUI."

-- Tukui Module
L.TUKUI_OPTIONS_NAME = "Tukui"
L.TUKUI_OPTIONS_TITLE = "Tukui"
L.TUKUI_OPTIONS_SUBTEXT = "Эти настройки влияют на поведение всех поддерживаемых элементов Tukui."
L.TUKUI_OPTIONS_ENABLED_TEXT = "Включено"
L.TUKUI_OPTIONS_ENABLED_TOOLTIP = "Включить или отключить модуль Tukui."
L.TUKUI_OPTIONS_NOTICE_TEXT = "|TInterface\\OptionsFrame\\UI-OptionsFrame-NewFeatureIcon:0:0:0:-1|t Поддержка Tukui скоро появится!"
